/**************************************************************************************************************************
**
**	Function: SEED MEDICATION FORMS : Mozambique Implementation
**
***************************************************************************************************************************/

SET IDENTITY_INSERT [dbo].[MedicationForm] ON
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (1, N'Ampola')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (2, N'Garrafa ')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (3, N'Cartucho')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (4, N'Preservativo')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (5, N'Creme')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (6, N'Disco para testes laboratoriais')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (7, N'Descartável')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (8, N'Cada')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (9, N'Gotas para os ouvidos')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (10, N'Elixir')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (11, N'Enema')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (12, N'Gás')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (13, N'Gel')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (14, N'Grânulos')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (15, N'Inalador')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (16, N'DIU')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (17, N'Líquido')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (18, N'Loção')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (19, N'Gotas nasais')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (20, N'Spray nasal')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (21, N'Net')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (22, N'Pomada')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (23, N'Gotas oftálmicas')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (24, N'Pomada oftálmica')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (25, N'Tiras oftálmicas')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (26, N'Gotas orais')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (27, N'Gel oral')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (28, N'Pessário')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (29, N'Pó')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (30, N'Tubo retal')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (31, N'Solução respiratória')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (32, N'Rod')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (33, N'Champô')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (34, N'Sólido')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (35, N'Solução')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (36, N'Spray')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (37, N'Supositório')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (38, N'Suspensão')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (39, N'Seringa')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (40, N'Xarope')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (41, N'Comprimido ou cápsula')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (42, N'Teste')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (43, N'Tintura')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (44, N'Emplastro transdérmico')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (45, N'Frasco')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (46, N'Desconhecido')
SET IDENTITY_INSERT [dbo].[MedicationForm] OFF