-- ***************** MEDICATION FORMS
SET IDENTITY_INSERT [dbo].[MedicationForm] ON
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (1, N'Ampoule')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (2, N'Bottle ')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (3, N'Cartridge')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (4, N'Condom ')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (5, N'Cream')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (6, N'Disc for lab testing')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (7, N'Disposable')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (8, N'Each')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (9, N'Ear drops')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (10, N'Elixir')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (11, N'Enema')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (12, N'Gas')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (13, N'Gel')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (14, N'Granules')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (15, N'Inhaler')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (16, N'IUD')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (17, N'Liquid')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (18, N'Lotion')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (19, N'Nasal drops')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (20, N'Nasal spray')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (21, N'Net')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (22, N'Ointment')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (23, N'Ophthalmic drops')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (24, N'Ophthalmic ointment')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (25, N'Ophthalmic strips')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (26, N'Oral drops')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (27, N'Oral gel')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (28, N'Packet')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (29, N'Pessary')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (30, N'Powder')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (31, N'Rectal tube')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (32, N'Respiratory solution')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (33, N'Rod')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (34, N'Shampoo')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (35, N'Solid')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (36, N'Solution')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (37, N'Spray')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (38, N'Suppository')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (39, N'Suspension')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (40, N'Syringe')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (41, N'Syrup')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (42, N'Tablet or capsule')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (43, N'Test')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (44, N'Tincture')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (45, N'Transdermal patch')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (46, N'Vial')
INSERT [dbo].[MedicationForm] ([Id], [Description]) VALUES (47, N'Unknown')
SET IDENTITY_INSERT [dbo].[MedicationForm] OFF