/**************************************************************************************************************************
**
**	Function: SEED MEDICATIONS
**
***************************************************************************************************************************/

-- ***************** MEDICATIONS
SET IDENTITY_INSERT [dbo].[Medication] ON
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (2, N'abacavir ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (3, N'abacavir + lamivudine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (4, N'acetazolamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (5, N'acetic acid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (6, N'acetylcysteine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (7, N'acetylsalicylic acid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (8, N'aciclovir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (10, N'albendazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (12, N'alcohol based hand rub', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (13, N'allopurinol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (15, N'all-trans retinoid acid (ATRA)', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (16, N'amidotrizoate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (17, N'amikacin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (18, N'amiloride', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (19, N'amiodarone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (20, N'amitriptyline', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (21, N'amlodipine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (22, N'amodiaquine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (23, N'amoxicillin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (24, N'amoxicillin + clavulanic acid  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (25, N'amoxicillin-clavulanate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (26, N'amphotericin B', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (27, N'ampicillin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (28, N'anastrozole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (29, N'anti-D immunoglobulin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (30, N'anti-rabies immunoglobulin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (31, N'anti-tetanus immunoglobulin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (32, N'anti-venom immunoglobulin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (33, N'artemether', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (34, N'artemether + lumefantrine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (35, N'artesunate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (36, N'artesunate + amodiaquine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (37, N'artesunate + mefloquine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (38, N'ascorbic acid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (39, N'asparaginase', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (40, N'atazanavir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (41, N'atenolol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (42, N'atracurium', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (43, N'atropine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (44, N'azathioprine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (45, N'azithromycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (46, N'barium sulfate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (47, N'BCG vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (48, N'beclometasone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (49, N'bedaquiline', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (50, N'bendamustine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (51, N'benzathine benzylpenicillin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (52, N'benznidazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (53, N'benzoyl peroxide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (54, N'benzyl benzoate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (55, N'benzylpenicillin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (56, N'betamethasone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (57, N'bevacizumab', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (58, N'bicalutamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (59, N'biperiden', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (60, N'bisoprolol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (61, N'bleomycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (62, N'budesonide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (63, N'bupivacaine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (64, N'buprenorphine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (65, N'caffeine citrate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (66, N'calamine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (67, N'calcium', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (68, N'calcium folinate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (69, N'calcium gluconate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (70, N'capecitabine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (71, N'capreomycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (72, N'carbamazepine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (73, N'carboplatin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (74, N'carvedilo', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (75, N'cefalexin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (76, N'cefazolin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (77, N'cefixime', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (78, N'cefotaxime', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (79, N'ceftazidime', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (80, N'ceftriaxone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (81, N'charcoal, activated', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (82, N'chlorambucil', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (83, N'chloramphenicol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (84, N'chlorhexidine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (85, N'chlorine base compound', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (86, N'chloroquine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (87, N'chloroxylenol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (88, N'chlorpromazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (89, N'cholecalciferol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (90, N'cholera vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (91, N'ciclosporin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (92, N'ciprofloxacin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (93, N'cisplatin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (94, N'clarithromycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (95, N'clindamycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (96, N'clofazimine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (97, N'clomifene', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (98, N'clomipramine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (99, N'clopidogrel  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (100, N'clotrimazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (101, N'cloxacillin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (102, N'clozapine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (103, N'coagulation factor IX', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (104, N'coagulation factor VIII  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (105, N'coal tar', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (106, N'codeine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (107, N'condoms', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (108, N'copper-containing device', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (109, N'cyclizine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (110, N'cyclopentolate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (111, N'cyclophosphamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (112, N'cycloserine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (113, N'cytarabine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (114, N'dacarbazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (115, N'daclatasvir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (116, N'dactinomycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (117, N'dalteparin  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (118, N'dapsone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (119, N'darunavir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (120, N'dasabuvir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (121, N'daunorubicin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (122, N'deferoxamine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (123, N'delamanid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (124, N'desmopressin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (125, N'dexamethasone ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (126, N'dexamethasone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (127, N'dextran 70', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (128, N'diaphragms', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (129, N'diazepam', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (130, N'diethylcarbamazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (131, N'digoxin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (132, N'diloxanide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (133, N'dimercaprol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (134, N'diphtheria antitoxin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (135, N'diphtheria vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (136, N'docetaxel', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (137, N'docusate sodium', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (138, N'dopamine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (139, N'doxorubicin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (140, N'doxycycline', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (142, N'efavirenz', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (143, N'efavirenz + emtricitabine + tenofovir  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (144, N'eflornithine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (145, N'emtricitabine + tenofovir  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (146, N'enalapril', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (147, N'enoxaparin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (148, N'entecavir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (149, N'ephedrine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (150, N'epinephrine (adrenaline)', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (151, N'ergocalciferol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (152, N'ergometrine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (153, N'erythromycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (154, N'estradiol cypionate + medroxyprogesterone acetate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (155, N'ethambutol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (156, N'ethambutol 400mg /isoniazid 150mg', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (157, N'ethanol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (158, N'ethinylestradiol +  norethisterone  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (159, N'ethinylestradiol + levonorgestrel  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (160, N'ethionamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (161, N'ethosuximide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (162, N'etonogestrel-releasing implant', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (163, N'etoposide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (164, N'ferrous salt', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (165, N'ferrous salt + folic acid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (166, N'filgrastim', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (167, N'fluconazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (168, N'flucytosine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (169, N'fludarabine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (170, N'fludrocortisone  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (171, N'fluorescein', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (172, N'fluorouracil', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (174, N'fluoxetine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (176, N'fluphenazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (177, N'folic acid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (178, N'fomepizole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (179, N'fresh-frozen plasma', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (180, N'furosemide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (182, N'gatifloxacin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (183, N'gemcitabine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (184, N'gemifloxacin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (185, N'gentamicin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (187, N'glibenclamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (188, N'gliclazide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (189, N'glucagon', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (190, N'glucose', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (191, N'glucose with sodium chloride', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (192, N'glutaral', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (193, N'glyceryl trinitrate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (194, N'griseofulvin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (195, N'Haemophilus influenzae type b vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (196, N'haloperidol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (197, N'halothane     ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (198, N'heparin sodium', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (199, N'hepatitis A vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (200, N'hepatitis B vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (201, N'homatropine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (202, N'HPV vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (203, N'hydralazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (204, N'hydrochlorothiazide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (205, N'hydrocortisone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (206, N'hydromorphone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (207, N'hydroxocobalamin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (208, N'hydroxycarbamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (209, N'hydroxychloroquine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (210, N'hyoscine butylbromide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (211, N'hyoscine hydrobromide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (212, N'ibuprofen', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (213, N'ifosfamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (214, N'imatinib', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (215, N'imipenem + cilastatin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (216, N'influenza vaccine (seasonal)  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (217, N'insulin injection (soluble)', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (218, N'intermediate-acting insulin  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (219, N'intraperitoneal dialysis solution', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (220, N'iodine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (221, N'iohexol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (222, N'ipratropium bromide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (223, N'irinotecan', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (224, N'isoflurane', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (225, N'Isoniazid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (226, N'isosorbide dinitrate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (227, N'ivermectin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (228, N'Japanese encephalitis vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (229, N'kanamycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (230, N'ketamine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (231, N'lactulose', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (232, N'lamivudine ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (233, N'lamivudine + nevirapine + stavudine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (234, N'lamivudine + nevirapine + zidovudine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (235, N'lamivudine + zidovudine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (236, N'latanoprost', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (237, N'ledipasvir + sofosbuvir   ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (238, N'leuprorelin  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (239, N'levamisole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (240, N'levodopa +  carbidopa', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (241, N'levofloxacin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (242, N'levonorgestrel', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (243, N'levonorgestrel-releasing implant', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (244, N'levonorgestrel-releasing intrauterine system', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (245, N'levothyroxine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (246, N'lidocaine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (247, N'lidocaine + epinephrine (adrenaline) ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (248, N'linezolid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (249, N'lithium carbonate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (250, N'loperamide  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (251, N'lopinavir + ritonavir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (252, N'loratadine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (253, N'lorazepam', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (254, N'Lugol''s solution', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (255, N'magnesium sulfate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (256, N'mannitol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (257, N'measles vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (258, N'mebendazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (259, N'medroxyprogesterone acetate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (260, N'mefloquine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (261, N'meglumine antimoniate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (262, N'meglumine iotroxate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (263, N'melarsoprol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (265, N'meningococcal meningitis vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (266, N'mercaptopurine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (267, N'meropenem', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (268, N'mesna', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (269, N'metformin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (270, N'methadone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (271, N'methotrexate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (272, N'methyldopa', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (273, N'methylprednisolone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (274, N'methylthioninium chloride', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (275, N'methylene blue', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (276, N'metoclopramide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (277, N'metoprolol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (278, N'metronidazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (279, N'miconazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (280, N'midazolam', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (281, N'mifepristone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (282, N'miltefosine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (283, N'misoprostol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (284, N'morphine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (285, N'moxifloxacin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (286, N'mumps vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (287, N'mupirocin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (288, N'nadroparin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (289, N'naloxone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (290, N'neostigmine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (291, N'nevirapine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (292, N'niclosamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (293, N'nicotinamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (294, N'nicotine replacement therapy (NRT)  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (295, N'nifedipine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (296, N'nifurtimox', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (297, N'nitrofurantoin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (298, N'nitrous oxide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (299, N'norethisterone enantate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (300, N'normal immunoglobulin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (301, N'nystatin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (302, N'ofloxacin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (303, N'ombitasvir + paritaprevir + ritonavir  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (304, N'omeprazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (305, N'ondansetron', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (307, N'oral rehydration salts', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (308, N'oseltamivir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (309, N'oxaliplatin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (310, N'oxamniquine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (311, N'oxycodone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (312, N'oxygen', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (313, N'oxytocin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (314, N'paclitaxel', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (315, N'p-aminosalicylic acid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (316, N'pancreatic enzymes', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (317, N'paracetamol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (318, N'paromomycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (319, N'pegylated interferon alfa (2a or 2b)', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (320, N'penicillamine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (321, N'pentamidine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (322, N'permethrin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (323, N'pertussis vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (324, N'phenobarbital  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (325, N'phenoxymethylpenicillin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (326, N'phenytoin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (327, N'phytomenadione', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (328, N'pilocarpine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (329, N'platelets ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (330, N'pneumococcal vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (331, N'podophyllum resin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (332, N'poliomyelitis vaccine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (333, N'polygeline', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (334, N'potassium chloride', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (335, N'potassium ferric hexacyano-ferrate(II) - 2H2O(Prussian blue)', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (336, N'potassium iodide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (337, N'potassium permanganate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (338, N'povidone iodine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (339, N'praziquantel', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (340, N'prednisolone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (341, N'primaquine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (342, N'procaine benzylpenicillin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (343, N'procarbazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (344, N'progesterone vaginal ring', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (345, N'propofol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (346, N'propranolol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (347, N'propylthiouracil', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (348, N'prostaglandin E', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (349, N'protamine sulfate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (350, N'prothionamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (351, N'pyrantel', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (352, N'pyrazinamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (353, N'pyridostigmine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (354, N'pyridoxine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (355, N'pyrimethamine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (356, N'quinine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (357, N'rabies vaccine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (358, N'ranitidine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (359, N'red blood cells', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (360, N'retinol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (361, N'ribavirin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (362, N'riboflavin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (363, N'rifabutin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (364, N'rifampicin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (365, N'rifampicin 150mg / isoniazid 150mg', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (366, N'rifampicin 150mg / isoniazid 75mg', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (367, N'rifampicin 150mg / isoniazid 75mg / pyrazinamide 400mg / ethambutol 275mg', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (368, N'rifampicin 150mg /isoniazid 75mg / ethambutol 275mg', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (369, N'rifampicin 60mg / isoniazid 30mg', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (370, N'rifampicin 60mg / isoniazid 30mg pyrazinamide 150mg', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (371, N'rifampicin 60mg / isoniazid 60mg', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (372, N'rifapentine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (373, N'risperidone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (374, N'ritonavir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (375, N'rituximab', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (376, N'rotavirus vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (377, N'rubella vaccine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (378, N'salbutamol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (379, N'salicylic acid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (380, N'saquinavir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (381, N'selenium sulfide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (382, N'senna', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (383, N'silver sulfadiazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (384, N'simeprevir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (385, N'simvastatin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (386, N'sodium calcium edetate ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (387, N'sodium chloride', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (388, N'sodium fluoride', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (389, N'sodium hydrogen carbonate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (390, N'sodium lactate, compound solution', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (391, N'sodium nitrite', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (392, N'sodium nitroprusside', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (393, N'sodium stibogluconate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (394, N'sodium thiosulfate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (395, N'sofosbuvir  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (396, N'spectinomycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (397, N'spironolactone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (398, N'stavudine ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (399, N'streptokinase', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (400, N'streptomycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (401, N'succimer', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (402, N'sulfadiazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (403, N'sulfadoxine + pyrimethamine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (404, N'sulfamethoxazole + trimethoprim  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (405, N'sulfasalazine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (407, N'suramin sodium', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (408, N'surfactant', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (409, N'sutezolid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (410, N'suxamethonium', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (411, N'tamoxifen', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (412, N'tenofovir disoproxil fumarate', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (413, N'terbinafine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (414, N'terizidone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (415, N'testosterone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (416, N'tetanus vaccine ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (417, N'tetracaine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (418, N'tetracycline', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (419, N'thiamine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (420, N'thioacetazone', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (421, N'thiopental', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (422, N'tick-borne encephalitis vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (423, N'timolol', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (424, N'tioguanine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (425, N'tranexamic acid', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (426, N'trastuzumab', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (427, N'triclabendazole', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (428, N'trimethoprim', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (429, N'tropicamide', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (430, N'tuberculin, purified protein derivative (PPD)', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (431, N'typhoid vaccine  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (432, N'urea', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (433, N'valganciclovir', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (434, N'valproic acid (sodium valproate)  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (435, N'vancomycin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (436, N'varicella vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (437, N'vecuronium', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (438, N'verapamil', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (439, N'vinblastine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (440, N'vincristine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (441, N'vinorelbine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (442, N'warfarin', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (443, N'water for injection', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (444, N'whole blood  ', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (445, N'xylometazoline', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (446, N'yellow fever vaccine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (447, N'zidovudine', 1, 0, N'Unknown', N'Unknown', 46)
INSERT [dbo].[Medication] ([Id], [DrugName], [Active], [PackSize], [Strength], [CatalogNo], [MedicationForm_Id]) VALUES (448, N'zinc sulfate', 1, 0, N'Unknown', N'Unknown', 46)
SET IDENTITY_INSERT [dbo].[Medication] OFF
